# Site settings
title: Pursue
author: Pursue
email: 348564768@qq.com
description: "This blog is ceated by Pursue"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://kkkkkxiaofei.github.io" # the base hostname & protocol for your site
name: "Pursue"
twitter_username: kkkkkxiaofei
github_username:  kkkkkxiaofei

# Build settings
markdown: kramdown


#Global params

# use 'jkeyll build' can add source files into destination
source: .
destination: ./_site
tab_categories: ['article','photo','music','movie','about']
keep_files: ['.js','.css']
css_links: [
             '/css/main.css',
             '/css/bootstrap.css'
           ]
js_links:  [
             '/lib/jquery-1.11.1.min.js',
             '/lib/jquery-tmpl.js',
             '/lib/knockout-3.3.0.js',
             '/lib/underscore.js',
             '/lib/bootstrap.js',
             # '/model/page.js',
             # '/model/movie.js',
             # '/model/photo.js',
             # '/model/article.js',
             # '/model/music.js',
             '/script/index.js'
           ]
post_css_links: [
             '/css/main.css',
             '/css/bootstrap.css',
             '/css/markdown.css'
           ]
post_js_links:  [
           ]



